MACRO(OSGSWIG_ADD_MODULE)

	# Parameters can't be looked up like this: ${ARGV${num}}
	
	SET(NAME   ${ARGV0})
	SET(TARGET ${ARGV1})
	
	SET(LIB_0 ${ARGV2})
	SET(LIB_1 ${ARGV3})
	SET(LIB_2 ${ARGV4})
	SET(LIB_3 ${ARGV5})
	SET(LIB_4 ${ARGV6})
	
	SET_SOURCE_FILES_PROPERTIES(${NAME}.i PROPERTIES CPLUSPLUS TRUE)
	
	SWIG_ADD_MODULE(${NAME} ${TARGET} ${NAME}.i)
	
	SWIG_LINK_LIBRARIES(${NAME} ${LIB_0} ${LIB_1} ${LIB_2} ${LIB_3} ${LIB_4})

ENDMACRO(OSGSWIG_ADD_MODULE)
